const APP_NAME = "GridGaming";

export const SET_AUTH_TOKENS = `${APP_NAME}/SET_AUTH_TOKENS`;
export const REFRESH_ACCESS_TOKEN = `${APP_NAME}/REFRESH_ACCESS_TOKEN`;
export const CLEAR_ON_SIGNOUT = `${APP_NAME}/CLEAR_ON_SIGNOUT`;
export const SET_USER_DATA = `${APP_NAME}/SET_USER_DATA`;
